In [ ]:
# Day 2 - Netflix Dataset Journey
## Searching Algorithms (Linear & Binary)

In [10]:
import psycopg2       #to connect to PostgreSQL
import pandas as pd   # to handles tables nicely

In [11]:
conn = psycopg2.connect(
    dbname="netflix_db",
    user="postgres",       # your username
    password="jovita", # replace with your password
    host="localhost",      # or 127.0.0.1
    port="5432"            # default PostgreSQL port
)

In [12]:
# Example: fetch first 10 rows from ratings table
df_ratings = pd.read_sql("SELECT * FROM ratings LIMIT 10;", conn)
df_ratings

C:\Users\jovit\AppData\Local\Temp\ipykernel_4800\669458072.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_ratings = pd.read_sql("SELECT * FROM ratings LIMIT 10;", conn)

   rating_id show_id  user_id  rating
0          1      s1      549       6
1          2      s2       26       3
2          3      s3      505       5
3          4      s4      625       4
4          5      s5      117       3
5          6      s6      204       4
6          7      s7       83       4
7          8      s8      392       2
8          9      s9      266       4
9         10     s10      300       3

In [14]:
df = pd.read_csv("C:/Users/jovit/Desktop/Netflix_Project/netflix_titles.csv")
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [17]:
conn.rollback()

In [18]:
with open("C:/Users/jovit/Desktop/Netflix_Project/SQL/day2_queries.sql", "r") as file:
    sql_script = file.read()

# Split into individual statements
queries = sql_script.split(";")

cursor = conn.cursor()
for query in queries:
    if "CREATE TABLE" not in query:   # skip table creation
        if query.strip() != "":
            cursor.execute(query)
conn.commit()
cursor.close()

In [ ]:
## Problem Statement
We want to search for a rating inside a list of Netflix ratings.
We will use two algorithms:
1. Linear Search
2. Binary Search

In [ ]:
### Linear Search
Linear search checks each element one by one until it finds the target.

In [23]:
# Linear search checks each element one by one
def linear_search(arr, target):
    for i in range(len(arr)):
        if arr[i] == target:   # compare each element with target
            return i           # return index if found
    return -1                  # return -1 if not found

# Example usage
ratings = [3, 5, 2, 4, 1]
print("Target found at index:", linear_search(ratings, 4))  # Output: 3

Target found at index: 3

In [ ]:
### Binary Search
Binary search is faster but requires the list to be sorted.

In [27]:
#Binary search requires sorted data
def binary_search(arr, target):
    low, high = 0, len(arr)-1
    while low <= high:
        mid = (low+high)//2
        if arr[mid]==target:
            return mid
        elif arr[mid]<target:
            low = mid +1 
        else:
            high = mid -1
    return
   # Example usage
ratings = sorted([3, 5, 2, 4, 1])  # must sort first
print("Target found at index:", binary_search(ratings, 4))  # Output: 3

Target found at index: 3